# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 main.py
            pylint main.py
            python3 tests/Jewishcal_test.py
            git push https://heroku:6f7a16f8-6a9d-41aa-9f43-9e5111e9acf2@git.heroku.com/gentle-caverns-68263.git master
            